server:
  port: 8080
spring:
  # RestTemplate的相关属性
  restTemplate:
    # 请求连接超时时间（单位：毫秒）
    connect-timeout: 5000
    # 读取响应的超时时间（单位：毫秒）
    read-timeout: 5000
    # 设置要使用的HttpMessageConverters，默认情况下会使用JdkHttpMessageConverters，
    # 如果需要自定义HttpMessageConverter，可以在这里添加相应的Bean名称
    message-converters:
      - stringHttpMessageConverter
      - mappingJackson2HttpMessageConverter
  
  # HttpMessageConverters的相关属性
  http:
    message-converters:
      # 配置StringHttpMessageConverter的编码（默认为“ISO-8859-1”）
      stringHttpMessageConverter:
        default-charset: UTF-8
      # 配置MappingJackson2HttpMessageConverter的ObjectMapper
      # 可以用于自定义Jackson的一些配置
      mappingJackson2HttpMessageConverter:
        object-mapper:
          serialization:
            indent-output: true
